name: Daily Email
on:
  schedule:
    - cron:  '0 8 * * 1-5'
jobs:
  daily-email:
    name: Send Email
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        run: |
          curl -X POST \
          -H "Authorization: Bearer $HOOK_ADMIN_TOKEN" \
          -H "Content-Type: application/json" \
          https://sjcchoops.herokuapp.com/hooks/sessions
        env:
          HOOK_ADMIN_TOKEN: ${{ secrets.HOOK_ADMIN_TOKEN }}