name: Daily Email
on: push
  # schedule:
  #   - cron:  '0 * * * *'
jobs:
  daily-email:
    name: Send Email
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        env:
          HOOK_ADMIN_TOKEN: iQCuteXF97TqXShZcx6QjY0WUxO7PjcY27hJ4HFGFZ/ozLy8KymCVsa7qRJnFZDI
        run: |
          curl -X POST -d '{"session":{"date":"2020-02-14"}}' \
          -H 'Authorization: Bearer $HOOK_ADMIN_TOKEN' \
          -H 'Content-Type: application/json' \
          https://sjcchoops.herokuapp.com/hooks/sessions